name: Validate

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  repository:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Validate repository
        run: ruby ./scripts/validate-repository.rb
